title: Marcelo Goncalves  # your name (or website title) here
logo: "/images/Marcelo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Python Connoisseur
  <br><br>
  Data Scientist
  <br><br>
  <a href="https://www.linkedin.com/in/marcelo-goncalves-82433744/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-cayman
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
